spring:
  application:
    name: loveable-clone

  datasource:
    url: jdbc:postgresql://localhost:5432/loveable_db
    username: postgres
    password: postgres

  jpa:
    open-in-view: false
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update   # dev only
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

jwt:
  secret-key: 32q4dasnbd17i623kjedfbn23qy4hfwsj
